-- Add comprehensive attraction set (map pins) for all 16 regions
insert into public.destinations ("id", "name", "category", "categoryName", "region", "location", "image", "rating", "reviews", "fee", "hours", "bestTime", "accessibility", "lat", "lng", "shortDesc", "fullDesc", "highlights", "nearbyHotels", "guideContact") values
('kwame-nkrumah-mausoleum', 'Kwame Nkrumah Memorial Park & Mausoleum', 'cultural', 'National Memorial', 'Greater Accra', 'Accra Central', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 5.5489, -0.1907, 'The final resting place of Ghana''s first president, featuring a bronze statue, eternal flame, and seaside gardens in the heart of Accra.', 'Kwame Nkrumah Memorial Park occupies the site where Ghana''s founding father and first president, Dr. Kwame Nkrumah, and his wife Fathia were laid to rest. Set near the Old Parliament on the Accra shoreline, the park pairs a dignified mausoleum and statue with tranquil gardens and the ocean outlook, telling the story of Ghana''s independence movement.', '["Bronze Statue of Nkrumah", "Eternal Flame", "Independence Garden Walk", "Accra Seafront Views"]', '[]', ''),
('manhyia-palace', 'Manhyia Palace Museum', 'historical', 'Royal Museum', 'Ashanti Region', 'Kumasi', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 6.7492, -1.587, 'The royal residence of the Ashanti kings of Kumasi, now a museum of Asante history, regalia, and court culture.', 'Manhyia Palace was built in 1925 as the new royal residence for the Ashanti monarch and has long been the ceremonial seat of the Asantehene of Kumasi. Today it operates as a museum preserving royal regalia, photographs, ceremonial stools, and the personal effects of successive Ashanti kings, offering visitors a vivid window into Asante court life.', '["Royal Regalia Exhibits", "Asantehene History", "Ceremonial Stools", "Kumasi Culture Overview"]', '[]', ''),
('lake-bosomtwe', 'Lake Bosomtwe Crater Lake', 'waterfalls', 'Crater Lake', 'Ashanti Region', 'Lake Bosomtwe, near Kumasi', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 6.5189, -1.466, 'A sacred circular crater lake, formed by a meteorite impact, ringed by lakeside villages and lively weekend boat trade.', 'Lake Bosomtwe lies within a 10.5 km meteorite crater surrounded by hilly Ashanti farmland. The lake has no outlet and is culturally sacred to the surrounding Asante villages, which fish it with traditional plank boats and canoes. Weekends draw families for boating, swimming, and lakeside picnics among the crater walls.', '["Crater Lake Boat Ride", "Sacred Lake Swimming", "Lakeside Village Walks", "Meteorite Crater Geology"]', '[]', ''),
('ahwiaa-woodcarving-village', 'Ahwiaa Woodcarving Village', 'cultural', 'Craft Village', 'Ashanti Region', 'Ahwiaa, near Kumasi', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 6.68, -1.54, 'A village of master carvers producing ceremonial Ashanti stools, royal figures, and fine wooden sculptures by hand.', 'Ahwiaa (Ahuwa) is Ghana''s leading woodcarving village, where families have carved for generations with simple chisels and scrapers. Craftspeople fashion the famous Ashanti ceremonial stools, filigree dancing stools, chiefs'' figures, and masks from tropical hardwoods, and welcome visitors to watch and commission pieces.', '["Live Carving Demonstrations", "Ceremonial Stools", "Custom Commission Ordering", "Ashanti Motifs"]', '[]', ''),
('fort-apollonia', 'Fort Apollonia', 'historical', 'UNESCO Heritage Site', 'Western Region', 'Beyin, near Nzulezo', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 5.024, -2.6, 'An 18th-century frontier fort turned regional museum, overlooking the journey to the Nzulezo stilt village.', 'Fort Apollonia was built by the Dutch around 1768 on a ridge above Beyin to guard trade routes on the Ankobra towards the Nzulezo lake. It was gutted by fire in the late 19th century and today its restored walls hold the Beyin Regional Museum, which traces the culture of the Nzema people and the surrounding natural landscape.', '["Restored Fort Ramparts", "Beyin Regional Museum", "Nzema Culture Exhibits", "Views over Lake Tadane"]', '[]', ''),
('ankasa-forest-reserve', 'Ankasa Conservation Area', 'national-parks', 'Rainforest & Wetland', 'Western Region', 'Near Axim / Elubo', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 5.27, -2.7, 'A pristine wet-evergreen rainforest and wetland near the Ivory Coast border, rich in primates, birds, and rare flora.', 'Ankasa Conservation Area in Ghana''s far southwest protects wet evergreen forest and the large Tanoe wetland system. It shelters Congo clawless otters, forest elephants, bongo antelopes, and abundant bird species along forest trails and the Ankobra watershed, offering guided nature walks into one of West Africa''s most biologically rich forests.', '["Guided Forest Walk", "Rare Birding", "Wetland Canoe Trails", "Primates & Wildlife"]', '[]', ''),
('sekondi-takoradi-beach', 'Sekondi-Takoradi Beach', 'coastal', 'Coastal Beach', 'Western Region', 'Sekondi-Takoradi', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 4.9, -1.76, 'Long golden-sand beaches and lagoons along the Sekondi-Takoradi coast, a relaxed seaside stretch of Ghana''s west.', 'The Sekondi-Takoradi coastline is lined with clean beaches, lagoon systems, and fishing communities. The palm-backed sands and gentle surf make it a favourite local getaway, with beachfront stalls serving fresh coconut and grilled fish and evening views over the Gulf of Guinea.', '["Golden Sand Beach", "Fresh Coconut Stalls", "Lagoon Walks", "Gulf of Guinea Sunsets"]', '[]', ''),
('techiman-history-museum', 'Techiman Heritage & Culture Museum', 'cultural', 'Heritage Museum', 'Bono Region', 'Techiman', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 7.59, -2.01, 'A community museum preserving the royal history, shrines, and oral traditions of the historic Bono (Brong) kingdom.', 'Techiman is the heart of the historic Bono (Brong) kingdom and its traditional area. The heritage museum gathers royal regalia, shrine artefacts, textiles, and the drumming traditions associated with the famous Apoo festival, giving visitors insight into one of Ghana''s oldest monarchical states.', '["Royal Regalia", "Apoo Festival Artefacts", "Brong Oral History", "Traditional Shrines"]', '[]', ''),
('kintampo-waterfalls', 'Kintampo Waterfalls', 'waterfalls', 'Waterfall', 'Bono East', 'Kintampo', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 8.16, -1.95, 'A series of cascades at the source of the Pumpum River, hidden in dense forest on the Kintampo plateau.', 'Kintampo Waterfulls are formed where the Pumpum River drops over a rocky outcrop in gallery forest, creating a chain of falls and plunge pools. Long a favourite picnic and trekking spot, the site offers nature trails, swimming holes, and the lush Kintampo Plateau scenery between the forested ravines.', '["Multiple Cascade Viewpoints", "Natural Swimming Pools", "Forest Nature Trails", "Kintampo Plateau Picnic"]', '[]', ''),
('gbewaa-palace', 'Gbewaa Palace (Daboya)', 'historical', 'Royal Site', 'Northern Region', 'Daboya, near Tamale', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 9.41, -0.75, 'The ancestral palace of the Dagbon kings, sacred to the royal Kayayei and the Damba festival traditions.', 'Gbewaa is the historic seat of the Dagbon (Dagbamba) royal family of Tamale. The palace compound holds royal graves and shrine houses, and remains the spiritual anchor of the Damba festival with its horse-riding displays and drumming. Visitors can trace the living heritage of northern Ghana''s chiefs.', '["Royal Palace Compound", "Dagbon Royal Graves", "Damba Festival Trails", "Northern Chieftaincy History"]', '[]', ''),
('navrongo-basilica', 'Navrongo Catholic Basilica', 'historical', 'Historic Church', 'Upper East Region', 'Navrongo', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 10.9, -1.08, 'Ghana''s oldest permanent Catholic structure, a red-brick basilica completed in 1906 by White Fathers missionaries.', 'The Basilica of Our Lady of Seven Sorrows in Navrongo is the oldest Catholic church in Ghana, built between 1882 and 1906 by the White Fathers in red-brick Romanesque style. Now a minor basilica with a bishop''s seat, it anchors the Christian heritage of the Upper East against the region''s Muslim and traditional histories.', '["Historic Basilica Walls", "1906 Mission Architecture", "Catholic Heritage Museum", "Navrongo Town Views"]', '[]', ''),
('bolgatanga-basketry-village', 'Bolgatanga Basket Weaving Village', 'cultural', 'Craft Village', 'Upper East Region', 'Bolgatanga', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 10.78, -1.25, 'The heartland of the famous Bolga baskets, where women weave vibrantly coloured grasses into export-quality baskets.', 'Bolgatanga (Bolgatanga) in the Upper East is famous across global retail for its brightly striped woven baskets. Local women harvest and dye elephant grass and weave intricate baskets, hampers, and homewares that are exported worldwide. Visitors can watch weaving and buy direct from the artisans'' cooperative.', '["Live Basket Weaving", "Bolgatanga Cooperative", "Direct Artisan Purchase", "Grass Dyeing Craft"]', '[]', ''),
('nania-slave-route', 'Nania Slave Route', 'historical', 'Heritage Trail', 'Upper East Region', 'Nania, near Paga', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 10.85, -1.1, 'A preserved section of the historic overland slave route with iron neck-ring trees and memorial stones.', 'Nania marks a chain of historic sites connected to the trans-Saharan slave trade across northern Ghana. Remnants include the famed iron neck-ring tree where captives were shackled, storage pits, and memorial stones. Interpretive trails place the painful history of the region''s slave routes in context.', '["Neck-Ring Tree", "Slave Route Trail", "Memorial Stones", "Guided Heritage Talk"]', '[]', ''),
('mount-gemi', 'Mount Gemi', 'national-parks', 'Adventure Mountain', 'Volta Region', 'Gbledi, near Afadjato', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 7.15, 0.68, 'The second-highest peak in Ghana, offering a steep forested ascent and views over the Togo borderland.', 'Mount Gemi (Afadja''s sibling peak) is one of southern Ghana''s highest summits, approached through misty montane forest near Afadjato. The climb rewards trekkers with panoramas across the Volta highlands and across the border into Togo, passing waterfalls and remnant forest along the ridge.', '["Summit Panorama", "Forest Trekking", "Togo Border Views", "Highland Birding"]', '[]', ''),
('tagbo-falls', 'Tagbo Falls', 'waterfalls', 'Waterfall', 'Volta Region', 'Liati Wote, near Afadjato', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 7.09, 0.55, 'A slender high cascade in the Afadjato highlands, best in the rainy season when the forest pools swell.', 'Tagbo Falls tumbles down a high rock face in the forested hills below Mount Afadjato. Its flow peaks after rains, creating frothing plunge pools and mist. The falls can be reached on foot from Liati Wote and combine naturally with the Afadjato summit and Gemi climbs on a mountain day-trip.', '["High Plunge Cascade", "Afadjato Combo Trek", "Forest Pools", "Highland Scenery"]', '[]', ''),
('bunso-eco-park', 'Bunso Honey & Palm Wine Eco-Park', 'national-parks', 'Eco-Park', 'Eastern Region', 'Bunso, Akuapem Ridge', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 6.32, -0.35, 'A nature and cultural park on the Akuapem ridge offering honey tasting, palm-wine trails, and lush walks.', 'Bunso Eco-Park sits on the heights of the Akuapem ridge in the Eastern Region. The park blends nature trails with revived traditions: a palm-wine distilling walk, honey production hives, and forest foraging experiences, all set within the cool mountain greenery of the Akuapem range.', '["Palm Wine Trail", "Honey Tasting", "Akuapem Ridge Walks", "Forest Gardening"]', '[]', ''),
('dambai-lake-volta', 'Lake Volta Shore at Dambai', 'national-parks', 'Lake & Jetty', 'Oti Region', 'Dambai, Oti', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 7.3, 0.1, 'The great artificial Lake Volta spreading out at Dambai, with fishing canoes and grand waterfront sunsets.', 'Dambai is the seat of the Oti region on the shore of Lake Volta, one of the world''s largest artificial reservoirs. The waterfront bustles with fishing canoes, ferries, and markets, and the broad lake horizon offers some of Ghana''s largest water vistas and sunsets.', '["Lake Volta Vistas", "Fishing Canoe Harbour", "Waterfront Markets", "Volta Sunsets"]', '[]', ''),
('gambaga-escarpment-lookout', 'Gambaga Lookout & Nahiley Escarpment', 'national-parks', 'Scenic Viewpoint', 'North East', 'Nalerigu / Gambaga', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 10.5, -0.42, 'Verdant escarpment viewpoints over the Mamprusi heartland and the rolling North East countryside.', 'The Gambaga-Nahiley escarpment in Ghana''s North East rises over the Mamprusi traditional area, with lookout points across dense farmland and hillside settlements. Its cool heights, waterfalls in the rains, and traditional towns make for scenic highland touring.', '["Escarpment Lookouts", "Mamprusi Farmland Views", "Hilltown Walks", "Rainy-Season Cascades"]', '[]', ''),
('wa-naa-palace', 'Wa Naa Palace', 'historical', 'Royal Site', 'Upper West', 'Wa, Upper West', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 10.95, -2.55, 'The old seat of the Wa Naa paramount chief, with preserved royal court buildings and northern savannah surroundings.', 'Wa Naa Palace in the far northwest recalls the chieftaincy system of the Waala (Wali) people. The compound retains traditional royal court structures and serves as a centre of local history near the regional capital, set amid the dry savannah of Ghana''s Upper West.', '["Royal Court Buildings", "Northern Savannah Setting", "Waala Chieftaincy History", "Central Architectural Style"]', '[]', ''),
('sefwi-wiawso-palace', 'Sefwi Wiawso Paramount Chief''s Palace', 'cultural', 'Royal Site', 'Western North', 'Sefwi Wiawso, Western North', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 6.2, -2.97, 'The traditional seat of the Sefwi paramount chieftaincy, set amid the forested hills of Ghana''s far west.', 'Sefwi Wiawso is the historic capital of the Sefwi people in Ghana''s Western North. The paramount chief''s palace compound preserves the region''s chieftaincy heritage, court structures, and surrounding cocoa-and-forest landscape, offering insight into the largely unexplored western hill country.', '[]', '[]', '+233 20 000 0000 (Wiawso Tourist Office)'),
('ahafo-cocoa-forest', 'Goaso Cocoa & Forest Belt', 'national-parks', 'Nature & Cocoa', 'Ahafo Region', 'Goaso, Ahafo Region', 'assets/images/attraction-placeholder.svg', 4.5, 0, 'Free Entry', 'Open Daily', 'Year-Round', 'Generally accessible', 6.8, -2.55, 'Rolling cocoa farms and gallery forest around Goaso, the agricultural heart of central-west Ghana.', 'The Ahafo Region around Goaso is one of Ghana''s principal cocoa-growing belts. Travelling the area reveals cocoa farms, palm swamps, and riverine forest with abundant birds, an off-the-beaten-path slice of rural Ashanti-Ahafo country.', '[]', '[]', '+233 20 000 0000 (Goaso Tourist Office)')
on conflict (id) do nothing;

-- Normalize boabeng-fiema region label to canonical name
update public.destinations set region = 'Bono East' where id = 'boabeng-fiema-monkey-sanctuary';

-- Append new attraction ids to their region records so region modals list them
update public.regions set destinations = destinations || '["kwame-nkrumah-mausoleum"]' where id = 'greater-accra';
update public.regions set destinations = destinations || '["manhyia-palace", "lake-bosomtwe", "ahwiaa-woodcarving-village"]' where id = 'ashanti';
update public.regions set destinations = destinations || '["fort-apollonia", "ankasa-forest-reserve", "sekondi-takoradi-beach"]' where id = 'western';
update public.regions set destinations = destinations || '["techiman-history-museum"]' where id = 'bono';
update public.regions set destinations = destinations || '["kintampo-waterfalls"]' where id = 'bono-east';
update public.regions set destinations = destinations || '["gbewaa-palace"]' where id = 'northern';
update public.regions set destinations = destinations || '["navrongo-basilica", "bolgatanga-basketry-village", "nania-slave-route"]' where id = 'upper-east';
update public.regions set destinations = destinations || '["mount-gemi", "tagbo-falls"]' where id = 'volta';
update public.regions set destinations = destinations || '["bunso-eco-park"]' where id = 'eastern';
update public.regions set destinations = destinations || '["dambai-lake-volta"]' where id = 'oti';
update public.regions set destinations = destinations || '["gambaga-escarpment-lookout"]' where id = 'north-east';
update public.regions set destinations = destinations || '["wa-naa-palace"]' where id = 'upper-west';
update public.regions set destinations = destinations || '["sefwi-wiawso-palace"]' where id = 'western-north';
update public.regions set destinations = destinations || '["ahafo-cocoa-forest"]' where id = 'ahafo';
