-- Supabase schema + seed for Ghana Kora Vista Tours
-- Run in Supabase SQL Editor (Dashboard > SQL > New query)


-- ============ TABLES ============
create table if not exists public.destinations (
  id text primary key,
  name text not null,
  category text,
  "categoryName" text,
  region text,
  location text,
  image text,
  rating numeric,
  reviews integer,
  fee text,
  hours text,
  "bestTime" text,
  accessibility text,
  lat numeric,
  lng numeric,
  "shortDesc" text,
  "fullDesc" text,
  highlights jsonb default '[]',
  "nearbyHotels" jsonb default '[]',
  "guideContact" text
);

create table if not exists public.festivals (
  id text primary key,
  name text not null,
  culture text,
  month text,
  duration text,
  location text,
  region text,
  image text,
  "shortDesc" text,
  "fullDesc" text,
  "keyRituals" jsonb default '[]'
);

create table if not exists public.regions (
  id text primary key,
  name text not null,
  capital text,
  abbreviation text,
  grid jsonb default '[]',
  span jsonb default '[]',
  blurb text,
  destinations jsonb default '[]',
  festivals jsonb default '[]'
);

create table if not exists public.practical_info (
  type text primary key,
  title text,
  badge text,
  content jsonb default '[]'
);

create table if not exists public.bookings (
  id text primary key,
  reference text unique,
  "fullName" text,
  email text,
  phone text,
  "arrivalDate" text,
  "arrivalTime" text,
  airport text,
  "flightNumber" text,
  travelers integer,
  services jsonb default '[]',
  "totalGHS" numeric default 0,
  "totalUSD" numeric default 0,
  "paymentMethod" text,
  "specialRequests" text,
  status text,
  "createdAt" text
);

create table if not exists public.wishlist (
  id serial primary key,
  "destinationId" text unique
);

-- seed destinations
insert into public.destinations ("id", "name", "category", "categoryName", "region", "location", "image", "rating", "reviews", "fee", "hours", "bestTime", "accessibility", "lat", "lng", "shortDesc", "fullDesc", "highlights", "nearbyHotels", "guideContact") values
('tafi-atome-monkey-sanctuary', 'Tafi Atome Monkey Sanctuary', 'national-parks', 'Wildlife Sanctuary', 'Volta Region', 'Tafi Atome, Hohoe District', 'assets/images/tafi_atome_monkeys_1.png', 4.9, 840, 'GHS 60 / $5', '8:00 AM – 5:00 PM Daily', 'Early Morning (7 AM – 10 AM)', 'Easy guided walking forest path', 6.9056, 0.385, 'Sacred sanctuary where friendly Mona monkeys roam freely and interact gently with visitors in a protected tropical forest.', 'Tafi Atome Monkey Sanctuary is a community-based eco-tourism project in the Volta Region of Ghana. For over 200 years, the sacred Mona monkeys (Cercopithecus mona) have been protected by local traditional beliefs, considered divine messengers of the gods. Visitors can feed bananas to friendly monkeys right from their hands while taking guided forest walks with local community guides.', '["Hand-feeding Mona Monkeys", "Sacred Forest Walk", "Traditional Ewe Village Experience", "Community Eco-Lodge"]', '["Tafi Atome Eco-Lodge", "Wli Water Heights Lodge", "Hohoe Executive Hotel"]', '+233 24 666 4321 (Tafi Atome Eco-Desk)'),
('boabeng-fiema-monkey-sanctuary', 'Boabeng-Fiema Monkey Sanctuary', 'national-parks', 'Wildlife Sanctuary', 'Bono East Region', 'Nkoranza North District', 'assets/images/tafi_atome_monkeys_2.jpg', 4.8, 720, 'GHS 70 / $6', '8:00 AM – 5:00 PM Daily', 'Year-Round (Best in dry season)', 'Shaded canopy walking trails', 7.7167, -1.7, 'Ghana''s famous sanctuary home to over 700 Mona monkeys and rare Geoffroy''s Pied Colobus monkeys living together peacefully.', 'Boabeng-Fiema is unique in Africa as the only sanctuary where two distinct species of monkeys—the Campbell''s Mona monkey and the black-and-white Geoffroy''s Pied Colobus monkey—live in close harmony near human villages. Local taboo strictly forbids harming the monkeys, and deceased monkeys are even buried with traditional funeral ceremonies in a special monkey cemetery.', '["Black & White Colobus Monkeys", "Sacred Monkey Cemetery", "Forest Canopy Nature Walk", "Nkoranza Cultural Heritage"]', '["Boabeng-Fiema Guest House", "Nkoranza Heritage Hotel", "Techiman Palace Hotel"]', '+233 20 555 9988 (Boabeng Tourism Committee)'),
('cape-coast-castle', 'Cape Coast Castle', 'historical', 'Historical Site', 'Central Region', 'Cape Coast, Atlantic Coast', 'assets/images/cape_coast_castle.png', 4.9, 1420, 'GHS 120 / $10', '9:00 AM – 4:30 PM Daily', 'Nov – Mar (Dry Season)', 'Wheelchair accessible lower courtyard', 5.1053, -1.2417, 'UNESCO World Heritage fortress standing over the Atlantic Ocean, preserving deep historical memory and colonial architecture.', 'Cape Coast Castle is one of about forty slave castles built on the Gold Coast of West Africa by European traders. Originally built by the Swedes in 1653 and later taken over by the British, it served as a major hub for the transatlantic slave trade. Visitors experience guided tours through the historic dungeons, the infamous ''Door of No Return'', and the upper museum detailing West African maritime history.', '["Door of No Return", "Historical Museum", "Cannon Ramparts", "Atlantic Ocean View"]', '["Coconut Grove Beach Resort", "Ridge Royal Hotel", "Oasis Beach Resort"]', '+233 24 555 0192 (GTA Certified Guide)'),
('kakum-national-park', 'Kakum National Park Canopy Walk', 'national-parks', 'National Park', 'Central Region', 'Cape Coast / Abrafo', 'assets/images/kakum_canopy.png', 4.8, 2180, 'GHS 150 / $12', '6:00 AM – 4:00 PM Daily', 'Early Morning (6 AM – 9 AM)', 'Moderate physical hiking involved', 5.35, -1.3833, 'Suspended 40 meters above the jungle floor, Kakum offers Africa''s most famous rainforest canopy walkway experience.', 'Kakum National Park covers 375 square kilometers of virgin tropical rainforest in southern Ghana. It is one of only three locations in Africa with a canopy walkway. Suspended across 7 tree-top bridges extending over 330 meters, visitors enjoy panoramic views of ancient hardwoods, rare birds, butterflies, and forest flora.', '["7-Bridge Canopy Walkway", "Guided Birdwatching", "Camping Grounds", "Rainforest Nature Trails"]', '["Kakum Rainforest Lodge", "Hans Cottage Botel", "Elmina Beach Resort"]', '+233 20 888 1234 (Ranger Desk)'),
('wli-waterfall', 'Wli Waterfalls', 'waterfalls', 'Waterfall', 'Volta Region', 'Hohoe, Volta Region', 'assets/images/wli_waterfall.png', 4.9, 950, 'GHS 80 / $7', '7:00 AM – 5:00 PM Daily', 'April – October (Peak Flow)', 'Flat 45-min jungle walk to Lower Falls', 7.1219, 0.5906, 'The highest waterfall in West Africa, cascading dramatically from a cliff face down into a fresh natural pool.', 'Wli Waterfall (locally known as Agumatsa Falls, meaning ''Allow Me to Flow'') drops over 80 meters down a sheer vertical rock face in the Agumatsa Wildlife Sanctuary. Surrounded by lush forest home to thousands of fruit bats, butterflies, and monkeys, visitors can swim in the cool, refreshing natural plunge pool.', '["Lower & Upper Falls Hike", "Fruit Bat Colony Sanctuary", "Natural Swimming Pool", "Agumatsa Forest Trail"]', '["Wli Water Heights Lodge", "Waterfall Sanctuary Lodge", "Gbadzeme Eco-Lodge"]', '+233 54 321 9876 (Wli Tourism Board)'),
('mole-national-park', 'Mole National Park Elephant Safari', 'national-parks', 'National Park', 'Savannah Region', 'Damongo, Northern Ghana', 'assets/images/mole_elephants.png', 4.9, 1640, 'GHS 200 / $16', '6:00 AM – 5:30 PM (Safari Hours)', 'Dec – April (Dry Season for Wildlife)', '4x4 Vehicle & Foot Safaris Available', 9.256, -1.849, 'Ghana''s largest wildlife refuge offering walking foot safaris alongside wild African elephants, antelopes, and baboons.', 'Spanning nearly 5,000 square kilometers of savannah wood and riparian forest, Mole is Ghana''s premier wildlife destination. It is famous for its close-up walking safaris where visitors can approach peaceful herds of wild African elephants on foot with experienced armed rangers.', '["Walking Foot Safaris", "Drive Safaris (4x4)", "Mole Motel Pool Outlook", "Larabanga Mosque Nearby"]', '["Zaina Lodge (Luxury Safari)", "Mole Motel", "Damongo Guest House"]', '+233 24 900 1122 (Park Headquarters)'),
('black-star-square', 'Black Star Square & Independence Arch', 'cultural', 'Cultural Landmark', 'Greater Accra', 'Accra Central Coast', 'assets/images/black_star_square.png', 4.7, 3100, 'Free Entry', 'Open 24/7 (Best during day)', 'Year-Round (Best at sunset)', 'Fully Paved & Accessible', 5.5486, -0.1931, 'The monumental heart of modern Ghana''s independence movement featuring the Black Star Gate and Eternal Flame.', 'Commissioned by Kwame Nkrumah to honor Ghana''s 1957 independence as the first sub-Saharan African nation to gain freedom from colonial rule. The site features the massive Black Star Gate, Independence Arch, the Flame of African Liberation, and seating for 30,000 spectators overlooking the Gulf of Guinea.', '["Independence Arch", "Black Star Gate", "Kwame Nkrumah Park Nearby", "Oceanfront Esplanade"]', '["Mövenpick Ambassador Hotel", "Kempinski Hotel Gold Coast City", "Alisa Hotel"]', '+233 30 222 4455 (Accra City Tours)'),
('paga-crocodile-pond', 'Paga Sacred Crocodile Pond', 'cultural', 'Sacred Sanctuary', 'Upper East Region', 'Paga, Burkina Faso Border', 'assets/images/Paga.jpg', 4.6, 580, 'GHS 50 / $4', '8:00 AM – 5:00 PM Daily', 'Dry Season (Nov – May)', 'Flat terrain near pond', 10.9936, -1.1128, 'Famous sacred pond where wild West African crocodiles live peacefully alongside villagers and visitors can pose with them.', 'Paga Crocodile Pond in northern Ghana is famous worldwide for its friendly, sacred crocodiles. According to local legend, the soul of every resident in Paga is tied to a crocodile in the pond. Guided by traditional caretakers, visitors can safely touch, pose with, and sit near tame crocodiles that emerge from the water.', '["Posing with Sacred Crocodiles", "Paga Slave Camp Nearby", "Burkina Border Market", "Nania Slave Route"]', '["Paga Eco-Lodge", "Navrongo Catering Rest House", "Bolgatanga Plaza Hotel"]', '+233 24 777 3311 (Paga Tourism Center)'),
('nzulezo-stilt-village', 'Nzulezo Stilt Village', 'historical', 'UNESCO Heritage Site', 'Western Region', 'Beyin, Lake Tadane', 'assets/images/ghana-stilt-village.jpg', 4.8, 890, 'GHS 100 / $8', '8:00 AM – 4:00 PM Daily', 'Rainy Season (Best water levels)', 'Canoe trip required across lake', 5.0167, -2.6, 'Ancient 500-year-old village built entirely on wooden stilts standing over Lake Tadane in western Ghana.', 'Nzulezo (meaning ''Surface of Water'' in the Nzema language) is a remarkable village built entirely on stilts over Lake Tadane. Founded over 500 years ago by migrants from Oualata, all structures, school, church, and walkways are suspended above the water. Visitors take a scenic 45-minute traditional canoe ride through raffia palm channels to reach the village.', '["Lake Tadane Canoe Ride", "Stilt Architecture & School", "Raffia Palm Jungle Canal", "Beyin Fort Apollonia"]', '["Maaha Beach Resort", "Lou Moon Eco-Lodge", "Beyin Beach Hotel"]', '+233 24 333 8822 (Nzulezo Tourist Board)'),
('mount-afadjato', 'Mount Afadja (Afadjato)', 'national-parks', 'Adventure Mountain', 'Volta Region', 'Liati Wote, Gbledi', 'assets/images/Afaja.jpg', 4.8, 1100, 'GHS 70 / $6', '6:00 AM – 4:00 PM Daily', 'Early Morning (Clear summit views)', 'Strenuous mountain hike', 7.1167, 0.5833, 'The highest mountain peak in Ghana (885m), offering breathtaking summit views over Togo and the Volta forest.', 'Mount Afadja (commonly called Afadjato) stands at 885 meters (2,904 ft) above sea level, making it the highest elevation in Ghana. Located near the Togo border, a challenging 2-hour summit hike rewards adventurers with panoramic views of lush mountain valleys, Tagbo Falls, and surrounding tropical rain forest.', '["Summit Peak View of Togo", "Tagbo Waterfall Hike", "Liati Wote Butterfly Sanctuary", "Mountain Trekking Trail"]', '["Tagbo Falls Lodge", "Hohoe Executive Hotel", "Wli Sanctuary Lodge"]', '+233 20 444 5566 (Liati Wote Eco-Desk)'),
('boti-waterfalls', 'Boti Waterfalls & Umbrella Rock', 'waterfalls', 'Waterfall', 'Eastern Region', 'Yilo Krobo, Koforidua', 'assets/images/boti .jpeg', 4.7, 1250, 'GHS 80 / $7', '8:00 AM – 5:00 PM Daily', 'June – October (Twin Falls Flow)', '250 stone steps to falls base', 6.1667, -0.2167, 'Famous twin waterfalls (''Male and Female'') nestled in the Huhunya forest alongside the gravity-defying Umbrella Rock.', 'Boti Falls is a seasonal twin waterfall located in the Eastern Region. The twin falls are referred to locally as the ''Male'' and ''Female'' falls; during high flow in the rainy season, they merge together in a sacred ''mating ceremony''. A 30-minute hike from the falls leads to the famous Umbrella Rock and a three-headed palm tree.', '["Twin Falls Mating Ceremony", "Umbrella Rock Balancing Formation", "3-Headed Palm Tree", "Forest Hike"]', '["Mac-Dic Royal Plaza Koforidua", "Capital View Hotel", "Boti Eco-Lodge"]', '+233 24 111 6655 (Boti Falls Tourist Desk)'),
('elmina-castle', 'Elmina Castle (St. George''s Castle)', 'historical', 'UNESCO Heritage Site', 'Central Region', 'Elmina, Central Coast', 'assets/images/Elimina.webp', 4.9, 1890, 'GHS 120 / $10', '9:00 AM – 4:30 PM Daily', 'Year-Round', 'Paved courtyards & historic stairs', 5.0844, -1.3492, 'The oldest European building in existence in sub-Saharan Africa, erected by the Portuguese in 1482.', 'St. George''s Castle in Elmina was constructed by Portuguese traders in 1482 as the first European trading post built on the Gulf of Guinea. Initially established for gold trading, it later became a central site of the transatlantic slave trade under Dutch and British control. Today, it stands as a UNESCO World Heritage site and powerful monument of remembrance.', '["Portuguese & Dutch Dungeons", "Female Slave Cells", "Governor''s Suite", "Elmina Fishing Harbor Overlook"]', '["Elmina Beach Resort", "Coconut Grove Beach Resort", "Golden Hill Parker Hotel"]', '+233 24 888 7766 (Elmina Castle Desk)'),
('larabanga-mosque', 'Larabanga Ancient Mosque', 'historical', 'Architectural Heritage', 'Savannah Region', 'Larabanga, near Mole Park', 'assets/images/Larabanga.webp', 4.7, 640, 'GHS 40 / $3', '8:00 AM – 5:30 PM Daily', 'Dry Season (Combines with Mole Safari)', 'Flat village walking access', 9.2197, -1.8603, 'Ghana''s oldest mosque built in 1421 in Sudanic-Sahelian architectural style, known as the ''Mecca of West Africa''.', 'Larabanga Mosque is an ancient mud-brick mosque founded in 1421 by Islamic trader Ayuba. Built using whitewashed mud, timber logs, and pyradmidal towers, it is the oldest existing mosque in Ghana and one of the most famous examples of Sudanic architecture in West Africa. It houses an ancient Koran believed to have descended from heaven.', '["Sudanese Mud-Brick Architecture", "Ancient Holy Koran Replica", "Larabanga Mystic Stone", "Mole Safari Stopover"]', '["Zaina Lodge", "Mole Motel", "Damongo Guest House"]', '+233 24 555 4321 (Larabanga Tourism Guild)'),
('aburi-botanical-gardens', 'Aburi Botanical Gardens', 'national-parks', 'Botanical Reserve', 'Eastern Region', 'Aburi, Akuapem Hills', 'assets/images/Aburi.webp', 4.7, 1950, 'GHS 50 / $4', '8:30 AM – 5:00 PM Daily', 'Year-Round (Cool mountain breeze)', 'Wide paved garden avenues', 5.8483, -0.1747, 'Historic 1890s hilltop garden retreat nestled in the cool Akuapem mountains featuring giant palm avenues and exotic trees.', 'Established in 1890 by the British colonial administration, Aburi Botanical Gardens spans 160 acres of lush mountain forest. Known for its majestic royal palm avenue, carved tree of life, exotic medicinal plants, and cool temperate climate, Aburi is a favorite weekend getaway just 45 minutes drive from Accra.', '["Royal Palm Tree Avenue", "Carved Tree of Life", "Old Helicopter Monument", "Cocoa Tree Demonstration Plot"]', '["Peduase Valley Resort", "Aburi Heights Hotel", "Hillburi Resort"]', '+233 20 222 9988 (Aburi Gardens Desk)'),
('bonwire-kente-village', 'Bonwire Kente Weaving Village', 'cultural', 'Craft Heritage', 'Ashanti Region', 'Bonwire, near Kumasi', 'assets/images/Kente.jpg', 4.8, 810, 'Free Entry (Shopping extra)', '8:00 AM – 5:00 PM (Mon – Sat)', 'Year-Round', 'Village workshop walking paths', 6.7833, -1.4833, 'The historic heartland of royal Ashanti Kente cloth weaving, where master weavers craft silk fabrics on wooden looms.', 'Bonwire is world-famous as the birth village of Kente cloth weaving in the Ashanti Kingdom. Legend has it that two brothers learned the art by observing a spider weaving its web. Today, visitors can watch master craftsmen operate hand looms, try weaving their own patterns, and purchase authentic royal Kente directly from artisan families.', '["Live Hand-Loom Weaving", "Custom Kente Ordering", "Kente Origin Legends", "Bonwire Kente Museum"]', '["Manhyia Palace Hotel", "Golden Tulip Kumasi", "Royal Basin Resort"]', '+233 24 444 1199 (Bonwire Weavers Guild)') on conflict (id) do nothing;

-- seed festivals
insert into public.festivals ("id", "name", "culture", "month", "duration", "location", "region", "image", "shortDesc", "fullDesc", "keyRituals") values
('aboakyer-festival', 'Aboakyer Festival (Deer Hunting Festival)', 'Effutu People of Winneba Traditional Area', 'May (1st Saturday in May)', '1 Week Celebration', 'Winneba', 'Central Region', 'assets/images/aboakyer_festival.jpg', 'Famous deer hunting ritual where rival Asafo warrior companies capture a live bushbuck deer unarmed to present to the Paramount Chief.', 'The Aboakyer festival is celebrated on the 1st Saturday in May by the Effutu people of Winneba in the Central Region. It commemorates their migration from the ancient Western Sudan Empire to their present settlement. The highlight features a fierce competitive deer hunt between two traditional Asafo warrior groups—the Dentsefo and Tuafo. The first group to capture a live, uninjured deer using only bare hands wins high prestige, presenting it to the Simpa Otuano royal stool.', '["Asafo Warrior Deer Hunt", "Royal Stool Consecration", "Durbar of Paramount Chiefs", "Highlife Musical Concerts"]'),
('homowo-festival', 'Homowo Festival', 'Ga People of Accra', 'August / September', '1 Month Festival Season', 'Accra, Tema, Ningo', 'Greater Accra Region', 'assets/images/homowo_festival.jpg', 'Meaning ''hooting at hunger'', celebrating victory over historical famine with traditional Kpokpoi food sharing and drumming.', 'Homowo is the most celebrated festival of the Ga people in Greater Accra. The word ''Homowo'' literally translates to ''hooting at hunger''. It commemorates a devastating famine that plagued the Ga ancestors during their migration to Accra before a miraculous bountiful harvest. Chiefs and family heads sprinkle traditional ''Kpokpoi'' (steamed cornmeal and palm oil soup) across family ancestral homes and streets while drumming and dancing.', '["Kpokpoi Ritual Sprinkling", "Twin Celebrations (Akweley Suma)", "Twin Drumming & Dancing", "Family Reconciliation Feasts"]'),
('adekyem-festival', 'Adekyem Festival', 'Akan People of Bechem', 'December', '3 Days', 'Bechem', 'Ahafo Region', 'assets/images/adekyem_festival.jpg', 'Derived from Akan ''Adekyem'' meaning ''gift distribution'', celebrating harvest bounty and community sharing.', 'Bechem is derived from the Akan phrase ''Adekyem'', which literally translates to a place where gifts or harvested items are shared. Celebrated annually in December, the chief and elders distribute symbolic gifts, agricultural harvest produce, and awards to outstanding community members while honoring ancestral spirits.', '["Harvest Gift Sharing", "Ancestral Libation Pouring", "Akan Fontomfrom Drumming", "Development Fundraiser"]'),
('apoo-festival', 'Apoo Festival', 'Bono People of Techiman & Sunyani', 'October', '1 Week', 'Techiman & Sunyani', 'Bono Region', 'assets/images/apoo_festival.jpg', 'A cleansing festival allowing citizens to speak honest truths to leaders and cleanse social grievances.', 'Apoo is an ancient purification festival celebrated by the Bono people of Techiman and Sunyani. The name comes from ''Apo'' meaning to reject or cleanse evil. During the festival week, citizens are permitted to publicly express grievances, critique chiefs and leaders constructively without penalty, bringing social harmony and spiritual cleansing.', '["Public Honest Critiques (Apoo Songs)", "Town Spiritual Cleansing", "Royal Durbar", "Traditional Pacification Shrines"]'),
('asafotufiam-festival', 'Asafotufiam Festival', 'Ga-Adangbe People of Ada', 'July – August (1st Week)', '1 Week', 'Ada Traditional Area', 'Greater Accra Region', 'assets/images/asafotufiam_festival.jpg', 'Warrior festival commemorating ancestral victories with musketry firing displays and colourful Volta river regattas.', 'Asafotufiam is celebrated by the chiefs and people of Ada in remembrance of ancient war achievements of their brave ancestors who fought for the settlement of Ada land. Asafo warrior groups dress in traditional battle armor, fire ceremonial muskets, and parade through the streets followed by boat racing along the Volta River estuary.', '["Ceremonial Musket Firing", "Volta Estuary Boat Regatta", "Asafo Company Reenactments", "Miss Ada Cultural Pageant"]'),
('bakatue-festival', 'Bakatue Festival', 'Elmina & Fante People', '1st Tuesday in July', '1 Week', 'Elmina', 'Central Region', 'assets/images/bakatue_festival.jpg', 'Meaning ''opening of the lagoon'', marking the start of the fishing season with royal canoe races and sea rituals.', 'Bakatue means ''the opening of the lagoon'' (Benya Lagoon). Celebrated by the chiefs and people of Elmina, the festival invokes ancestral blessings for a bountiful fishing harvest. The Paramount Chief casts a net into the lagoon 3 times, after which colorful decorated canoes race across the water in front of Castle Elmina.', '["Casting of the Royal Net", "Benya Lagoon Canoe Race", "Royal Palanquin Procession", "Seafood Festival & Highlife"]'),
('damba-festival', 'Damba Festival', 'Dagbamba, Gonja, Mamprusi & Waala People', 'July – August', '1 Week', 'Tamale, Yendi, Wa', 'Northern & Savannah Regions', 'assets/images/damba_festival.jpg', 'Vibrant Northern festival featuring royal horse riding displays, traditional Batakari smocks, and talking drum performances.', 'Damba is one of the most prominent cultural festivals in Northern Ghana, celebrated by the Dagbamba, Gonja, Mamprusi, and Waala ethnic groups. Originally marking the birth of Prophet Muhammad, it has evolved into a glorious display of chieftaincy, horse-riding choreography, traditional Northern smocks (Batakari), and intricate talking drum (Dondo) dancing.', '["Somokun (Rice Picking Ritual)", "Royal Horse Dancing Display", "High Chiefs Procession", "Batakari Fashion & Dance Showcase"]'),
('dipo-festival', 'Dipo (Puberty Rites) Festival', 'Krobo People of Somanya & Manya Krobo', 'February / April', '4 Days', 'Somanya & Odumase Krobo', 'Eastern Region', 'assets/images/dipo_festival.jpg', 'Ancient initiation rites ushering young women into womanhood, adorned in famous Krobo glass beads and royal attire.', 'Dipo is a traditional puberty rite celebrated by the Krobo people of the Eastern Region. It marks the transition of young maidens from adolescence into womanhood. Initiates are adorned with precious Krobo glass beads, silk cloths, and woven hats, performing the traditional Klama dance on sacred initiation stones.', '["Sacred Stone Cleansing (Tefo)", "Klama Dance Performance", "Adornment with Royal Krobo Beads", "Initiation Certification"]'),
('fao-festival', 'FAO Harvest Festival', 'Kassena-Nankana People', 'January', '3 Days', 'Navrongo', 'Upper East Region', 'assets/images/fao_festival.jpg', 'Thanksgiving harvest festival featuring traditional horn blowing, shield dancing, and millet harvest celebrations.', 'FAO is celebrated by the Kassena-Nankana people of Navrongo to thank the Almighty God and ancestral spirits for a successful agricultural harvest season. Farmers display their largest crops, and traditional horn-blowers and shield warriors perform celebratory dances.', '["Harvest Thanksgiving Libation", "Traditional Horn & Flute Music", "Warrior Shield Dance", "Agricultural Produce Exhibition"]'),
('fetu-afahye-festival', 'Fetu Afahye Festival', 'Oguaa People of Cape Coast', 'September (1st Saturday)', '1 Week', 'Cape Coast', 'Central Region', 'assets/images/fetu_afahye_festival.jpg', 'Celebrated to purify Oguaa land of historic epidemics and invoke blessings from the 77 traditional deities.', 'Fetu Afahye is celebrated by the Oguaa people of Cape Coast. It commemorates a historic plague that was eradicated through ancestral prayers to 77 local deities. Highlights include a grand procession of paramount chiefs carried in opulent palanquins under giant royal umbrellas, accompanied by Asafo drum beats.', '["Pouring Libation to 77 Deities", "Asafo Warriors Parade", "Grand Durbar of Chiefs", "Cape Coast Street Carnival"]'),
('gologo-festival', 'Gologo Festival', 'Talensi People of Tengzug', 'March', '3 Days', 'Tengzug, Talensi', 'Upper East Region', 'assets/images/gologo_festival.jpg', 'Pre-planting festival seeking rain and bountiful soil fertility from the sacred Tengzug rock shrines.', 'Gologo is celebrated by the Talensi people living amongst the majestic granitic rocks of Tengzug. Held in March before the rainy season, worshippers gather at the ancient Golib cave shrine to pray for rain, bumper grain harvests, and good health for all families.', '["Golib Shrine Invocations", "Pre-Planting Rain Rituals", "Sacred Rock Cave Chanting", "Community Communal Feast"]'),
('hogbetsotso-festival', 'Hogbetsotso Festival', 'Anlo Ewe People', 'November (1st Saturday)', '1 Week', 'Anloga', 'Volta Region', 'assets/images/hogbetsotso_festival.jpg', 'Commemorating the historic escape of the Ewe people from ancient tyrannical rule, featuring famous backward walking dances.', 'Hogbetsotso (pronounced ''Hogbe-tso-tso'') is celebrated by the Anlo Ewe people of the Volta Region. It commemorates their historic migration escape from Notsie in present-day Togo to avoid the tyranny of King Agorkoli. During the festival, dancers perform the Agbadza and Atsiagbekor dances, reenacting their backward walking strategy used to deceive pursuers.', '["Reenactment of Backward Escape Walk", "Agbadza & Atsiagbekor Dances", "Peace & Reconciliation Purification", "Durbar of Ewe Chiefs"]'),
('kloyo-sikplemi-festival', 'Kloyo Sikplemi Festival', 'Yilo Krobo People', 'November', '1 Week', 'Somanya', 'Eastern Region', 'assets/images/kloyo_sikplemi_festival.jpg', 'Commemorating the Krobo ancestors'' relocation from the Kloyo Mountain to their present lowlands.', 'Kloyo Sikplemi is celebrated by the Yilo Krobo traditional area. It commemorates the historic eviction of their ancestors from the Kloyo mountain reserve by British colonial forces in 1892. The festival features a pilgrimage hike up the sacred Kloyo Mountain.', '["Sacred Mountain Pilgrimage Hike", "Ancestral Tribute Libations", "Fontomfrom Drumming", "Yilo Krobo Cultural Pageant"]') on conflict (id) do nothing;

-- seed regions
insert into public.regions ("id", "name", "capital", "abbreviation", "grid", "span", "blurb", "destinations", "festivals") values
('greater-accra', 'Greater Accra', 'Accra', 'GA', '[3, 0]', '[1, 1]', 'Ghana''s national capital and economic heartbeat, home of the Independence Arch and the coastal Ga heartland.', '["black-star-square"]', '["homowo-festival", "asafotufiam-festival"]'),
('central', 'Central Region', 'Cape Coast', 'CE', '[3, 2]', '[1, 1]', 'Historic Cape Coast and Elmina castles, the Kakum rainforest canopy, and the Effutu deer-hunting tradition.', '["cape-coast-castle", "kakum-national-park", "elmina-castle"]', '["aboakyer-festival", "bakatue-festival", "fetu-afahye-festival"]'),
('western', 'Western Region', 'Sekondi-Takoradi', 'WE', '[2, 2]', '[1, 1]', 'Ghana''s oil and mineral coast, home of the stilt village of Nzulezo and lush rainforests.', '["nzulezo-stilt-village"]', '[]'),
('western-north', 'Western North', 'Sefwi Wiawso', 'WN', '[2, 1]', '[1, 1]', 'Cocoa country and gold-rich forests of the Sefwi people in western Ghana.', '[]', '[]'),
('ashanti', 'Ashanti Region', 'Kumasi', 'AH', '[2, 0]', '[1, 1]', 'The royal heartland of the Asante Kingdom, famed for the Manhyia Palace and Bonwire kente weaving.', '["bonwire-kente-village"]', '[]'),
('eastern', 'Eastern Region', 'Koforidua', 'ER', '[1, 1]', '[1, 1]', 'The green garden region of Aburi, twin Boti waterfalls, and the Krobo Dipo puberty rites.', '["boti-waterfalls", "aburi-botanical-gardens"]', '["dipo-festival", "kloyo-sikplemi-festival"]'),
('volta', 'Volta Region', 'Ho', 'VR', '[1, 2]', '[1, 1]', 'The Ewe heartland of the Anlo people — monkey sanctuaries, Wli waterfall, Mount Afadjato and Mount Gemi.', '["tafi-atome-monkey-sanctuary", "wli-waterfall", "mount-afadjato"]', '["hogbetsotso-festival"]'),
('oti', 'Oti Region', 'Dambai', 'OT', '[1, 3]', '[1, 1]', 'A northern-Volta borderland along Lake Volta, home of the Nkonya people.', '[]', '[]'),
('bono', 'Bono Region', 'Sunyani', 'BO', '[0, 0]', '[1, 1]', 'The historic Bono (Brong) kingdom of Techiman, land of the Apoo festival.', '[]', '["apoo-festival"]'),
('bono-east', 'Bono East', 'Techiman', 'BE', '[0, 1]', '[1, 1]', 'Home of the Boabeng-Fiema monkey sanctuary and Lake Volta''s northern catchments.', '["boabeng-fiema-monkey-sanctuary"]', '[]'),
('ahafo', 'Ahafo Region', 'Goaso', 'AF', '[1, 0]', '[1, 1]', 'Forest-rich cocoa and timber lands of the Akan people, home of the Adekyem festival.', '[]', '["adekyem-festival"]'),
('savannah', 'Savannah Region', 'Damongo', 'SV', '[-1, 0]', '[1, 1]', 'Northern savannah grasslands home of Mole National Park and the Larabanga Ancient Mosque.', '["mole-national-park", "larabanga-mosque"]', '["damba-festival"]'),
('northern', 'Northern Region', 'Tamale', 'NO', '[-1, 1]', '[1, 1]', 'The Dagbon kingdom of Tamale, grandest stage of the Damba horse-and-drum festival.', '[]', '["damba-festival"]'),
('north-east', 'North East', 'Nalerigu', 'NE', '[-1, 2]', '[1, 1]', 'The Mamprusi heartland, gateway to the Gambaga escarpment.', '[]', '[]'),
('upper-west', 'Upper West', 'Wa', 'UW', '[-2, 0]', '[1, 1]', 'The far northwest, known for the Wa Naa palace and the Gologo harvest festival.', '[]', '[]'),
('upper-east', 'Upper East', 'Bolgatanga', 'UE', '[-2, 1]', '[1, 1]', 'The far northeast of dry savannah and sacred Paga crocodiles, famed for Bolga baskets.', '["paga-crocodile-pond"]', '["fao-festival", "gologo-festival"]') on conflict (id) do nothing;

-- seed practical_info
insert into public.practical_info ("type", "title", "badge", "content") values
('getting-around', 'Getting Around Ghana', 'Transportation Guide', '"<h4>Domestic Flights</h4><p>PassionAir and Africa World Airlines (AWA) fly daily between Accra (ACC), Kumasi (KMS), Tamale (TML), and Takoradi (TKD).</p><h4>Ride Hailing & Taxis</h4><p>Uber, Yango, and Bolt operate extensively throughout Greater Accra and Kumasi. Local orange-fender taxis are also widely available.</p><h4>Tro-Tros & Intercity Coaches</h4><p>Tro-tros (shared minibuses) are the quintessential Ghanaian commute. For long distances, VIP Jeoun and STC offer comfortable air-conditioned coaches.</p>"'),
('flight-visa', 'Flight & Visa Requirements', 'Travel Documentation', '"<h4>Visa on Arrival & E-Visa</h4><p>Ghana offers online e-Visa applications and Visa on Arrival for ECOWAS citizens, African Union passport holders, and during December in GH season.</p><h4>Major Airlines Serving Accra (ACC)</h4><p>Kotoka International Airport is served by Delta, British Airways, Emirates, KLM, Qatar Airways, Ethiopian Airlines, and Turkish Airlines.</p><h4>Yellow Fever Certificate</h4><p>A valid international yellow fever vaccination card is mandatory for all incoming travelers over 9 months of age.</p>"'),
('practical-info', 'Practical Information & Tips', 'Essential Tourist Tips', '"<h4>Currency & Mobile Money (MoMo)</h4><p>The currency is the Ghana Cedi (GHS). Mobile Money (MTN MoMo) and cards are used everywhere in cities, but carry cash when visiting rural areas.</p><h4>Language & Greetings</h4><p>English is the official language. Learning basic Twi greetings like <em>Akwaaba</em> (Welcome), <em>Eti sen?</em> (How are you?), and <em>Medaase</em> (Thank you) will warm every heart!</p><h4>Power & Adapters</h4><p>Ghana uses Type G 3-pin British plugs (230V, 50Hz). Pack a universal travel adapter and power bank for safari trips.</p>"') on conflict (type) do nothing;


-- ============ ROW LEVEL SECURITY ============
alter table public.destinations enable row level security;
alter table public.festivals enable row level security;
alter table public.regions enable row level security;
alter table public.practical_info enable row level security;
alter table public.bookings enable row level security;
alter table public.wishlist enable row level security;

drop policy if exists "public read destinations" on public.destinations;
create policy "public read destinations" on public.destinations for select using (true);
drop policy if exists "public read festivals" on public.festivals;
create policy "public read festivals" on public.festivals for select using (true);
drop policy if exists "public read regions" on public.regions;
create policy "public read regions" on public.regions for select using (true);
drop policy if exists "public read practical_info" on public.practical_info;
create policy "public read practical_info" on public.practical_info for select using (true);

drop policy if exists "public insert bookings" on public.bookings;
create policy "public insert bookings" on public.bookings for insert with check (true);
drop policy if exists "public read bookings" on public.bookings;
create policy "public read bookings" on public.bookings for select using (true);

drop policy if exists "public all wishlist" on public.wishlist;
create policy "public all wishlist" on public.wishlist for all using (true) with check (true);
